homogeneous data <br>
multidimension <br>

table of numbers, index by numbers

In [1]:
import numpy as np

In [2]:
lista = [4, 7, 9]
tupa = (7, 2, 11)

In [3]:
na = np.array([lista, tupa])

In [4]:
print(na)

[[ 4  7  9]
 [ 7  2 11]]


In [5]:
type(na)

numpy.ndarray

In [6]:
na.dtype

dtype('int64')

#### ndarray.ndim
number of axes

#### ndarray.shape
dimensions of array

#### ndarray.size
total number of elements

#### ndarray.dtype
numpy datatypes (ex,: int64, int32, object....)

#### ndarray.data
actual elements
instead of data we acces the elements using index

In [8]:
nb = np.array([4, 7, 8])

In [10]:
na = np.array([lista, tupa], dtype=float)

In [11]:
print(na)

[[ 4.  7.  9.]
 [ 7.  2. 11.]]


In [12]:
nc = np.zeros((3, 4))

In [13]:
print(nc)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [14]:
nd = np.ones((3, 4))

In [15]:
print(nd)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [16]:
np.linspace(0, 2, 5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [18]:
np.sin([10, 20])

array([-0.54402111,  0.91294525])

In [19]:
ne = np.arange(4)

In [20]:
ne

array([0, 1, 2, 3])

In [21]:
nf = np.array([4, 6, 7, 8])

In [22]:
nf

array([4, 6, 7, 8])

In [23]:
ne

array([0, 1, 2, 3])

In [24]:
nf - ne

array([4, 5, 5, 5])

In [25]:
nf * ne

array([ 0,  6, 14, 24])

In [26]:
nb = np.array([ne, nf])

In [27]:
nb

array([[0, 1, 2, 3],
       [4, 6, 7, 8]])

In [28]:
ng = np.arange(8).reshape(2,4)

In [29]:
ng

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [30]:
ng @ nb

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 4)

In [32]:
nb = np.array([ne, nf, (4, 7, 1, 9), (6, 3, 4, 1)])

In [33]:
ng = np.arange(16).reshape(4, 4)

In [34]:
nb

array([[0, 1, 2, 3],
       [4, 6, 7, 8],
       [4, 7, 1, 9],
       [6, 3, 4, 1]])

In [35]:
ng

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [36]:
nb @ ng

array([[ 56,  62,  68,  74],
       [176, 201, 226, 251],
       [144, 165, 186, 207],
       [ 56,  70,  84,  98]])

In [37]:
nb * ng

array([[ 0,  1,  4,  9],
       [16, 30, 42, 56],
       [32, 63, 10, 99],
       [72, 39, 56, 15]])

In [39]:
nb[2,3]

9

In [40]:
nb.reshape(8, 2)

array([[0, 1],
       [2, 3],
       [4, 6],
       [7, 8],
       [4, 7],
       [1, 9],
       [6, 3],
       [4, 1]])

In [41]:
nb.reshape(1, -1)

array([[0, 1, 2, 3, 4, 6, 7, 8, 4, 7, 1, 9, 6, 3, 4, 1]])

3a + b + 2c = 5 <br>
a + 2b + c = 4 <br>
a + b = 21 <br>

In [42]:
A = np.array([[3, 1, 2], [1, 2, 1], [1, 1, 0]])

In [44]:
B = np.array([4, 5, 21])

In [45]:
sol = np.linalg.solve(A,B)

In [46]:
sol

array([ 14.25,   6.75, -22.75])

2x4 + 3x3 + 11x = 200 <br>
2x4 + 3x3 + 11x - 200 <br>

In [50]:
np.roots([2, 3, 0, 11, -200])

array([-3.76378618+0.j        , -0.22860214+3.11643975j,
       -0.22860214-3.11643975j,  2.72099046+0.j        ])